plank:
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190416-efb77f1e2"
      initupload: "gcr.io/k8s-prow/initupload:v20190416-efb77f1e2"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190416-efb77f1e2"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190416-efb77f1e2"
    gcs_configuration:
      bucket: "kubernetes-jenkins"
      path_strategy: "legacy"
      default_org: "figo"
      default_repo: "k8s-conformance-ci"
    gcs_credentials_secret: "service-account"

presubmits:
  figo/k8s-conformance-ci:
  - name: test-presubmit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
